### ISSUE TITLE
How to perform a manual backup of the SQLite database via FTP only?

### ISSUE THREAD

**Issue by EidrianGM** [aaemnnosttv/wp-sqlite-integration#4]
Hi! 

I tried to change all the links in my Wordpress from http to https using the plugin "Search and Replace" but this lead to an issue and now I no longer can access the wp-admin page. 

Is there a way to backup or edit the database by exclusively using FTP? 

Thanks for this plugin, it allows the University of Granada to have personal Wordpress pages.

**Comment by aaemnnosttv** [comment]
Hi there! Making a backup is as simple as copying the database file. By default this is in `wp-content/database/.ht.sqlite`

Just a heads up that this plugin isn't actively maintained. See https://github.com/aaemnnosttv/wp-sqlite-db which provides the core functionality in a single file without the plugin 👍
